      SUBROUTINE ADDNUMTOSTRING(STRING,NUMBER)

      IMPLICIT DOUBLE PRECISION (A-H,O-Z)

      CHARACTER*(*) STRING

      ISNUM=NUMBER
      DO I=LEN(STRING),1,-1
      IF (STRING(I:I) .NE. ' ') GOTO 10
      ENDDO
10    ISTRLEN=I

      NODIG=INT(LOG10(1.0*ISNUM+0.2))+1
      DO I=NODIG,1,-1
      NUM=ISNUM/10**(I-1)
      STRING(ISTRLEN+1:ISTRLEN+1)=CHAR(48+NUM)
      ISTRLEN=ISTRLEN+1
      ISNUM=ISNUM-NUM*10**(I-1)
      ENDDO

      END SUBROUTINE ADDNUMTOSTRING
